language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^support\/.*$/

script:
  - if [ "$CXX" == "g++" ]; scons compiler=`which $CXX` enable_gcov=True ; fi
  - if [ "$CXX" == "clang++" ]; scons compiler=`which $CXX` ; fi
  - ./run_tests --gtest_shuffle

notifications:
  email:
    recipients: pawel.kieliszczyk@gmail.com
    on_success: change
    on_failure: always
