language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^support\/.*$/

script:
  - scons
  - ./run_tests —-gtest_shuffle

notifications:
  recipients:
    - pawel.kieliszczyk@gmail.com
  email:
    on_success: change
    on_failure: always
