language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - develop

script:
  - scons
  - ./run_tests

notifications:
  email:
    recipients: pawel.kieliszczyk@gmail.com
    on_success: change
    on_failure: always
