language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^support\/.*$/

before_script:
  - which clang
  - which clang++
  - echo $PATH

script:
  - scons compiler=$CXX
  - ./run_tests --gtest_shuffle

notifications:
  email:
    recipients: pawel.kieliszczyk@gmail.com
    on_success: change
    on_failure: always
