language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^support\/.*$/

before_install:
  - sudo pip install cpp-coveralls

script:
  - if [ "$CXX" == "g++" ]; then scons compiler=`which $CXX` enable_gcov=True ; fi
  - if [ "$CXX" == "clang++" ]; then scons compiler=`which $CXX` ; fi
  - bin/test --gtest_shuffle

after_success:
  - if [ "$CXX" == "g++" ]; then coveralls --root bin --exclude bin/libraries --exclude bin/tests --gcov-options '\-lp' ; fi

notifications:
  email:
    recipients: pawel.kieliszczyk@gmail.com
    on_success: change
    on_failure: always
