Import('env')
local_env = env.Clone()


local_env.AppendUnique(CPPPATH = ["../googletest/gtest-1.7.0"])
local_env.AppendUnique(CPPPATH = ["../googletest/gtest-1.7.0/include"])
local_env.AppendUnique(CPPPATH = ["gmock-1.7.0"])
local_env.AppendUnique(CPPPATH = ["gmock-1.7.0/include"])


source_files = ["gmock-1.7.0/src/gmock-all.cc"]


program = local_env.StaticLibrary('gmock', source_files)
env.Alias('gmock', '.')
